# Docker Compose para entorno de testing
# Incluye servicios adicionales solo para tests

services:
  # Servicio WireMock para tests
  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock-testing
    ports:
      - "8089:8080"
    networks:
      - app-network
    environment:
      - WIREMOCK_OPTIONS=--verbose
    volumes:
      - ./wiremock-stubs:/home/wiremock/mappings:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Override auth-api para usar WireMock en testing
  auth-api:
    depends_on:
      - zipkin
      - wiremock
    environment:
      USERS_API_ADDRESS: http://wiremock-testing:8080
      ENV_MODE: testing

networks:
  app-network:
    driver: bridge